
  

entitymanager:
  packagesToScan: com 
 
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
---

server:
  servlet:
    context-path: /store
  port: 8080

spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:h2:~/test 
    username: SA
    #password:
    driverClassName: org.h2.Driver
    defaultSchema: 
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect 
---

server:
  servlet:
    context-path: /store
  port: 8080

spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/boutiq14_mbogni
    username: root 
    #password: mypassword
    driverClassName: com.mysql.jdbc.Driver 
    defaultSchema: 
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true 
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect 

